# Generated by Django 4.1.4 on 2023-01-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hustlers', '0002_hustlerprofile_delete_clientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hustlerprofile',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='hustlerprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='hustlerprofile',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='hustlerprofile',
            name='work_email',
        ),
        migrations.AddField(
            model_name='hustlerprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hustlerprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='establishment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='gh_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='ig_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='li_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='pi_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='pp_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/profile_imgs'),
        ),
        migrations.AlterField(
            model_name='hustlerprofile',
            name='tw_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
