# Generated by Django 4.1.4 on 2023-01-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hustlers', '0003_remove_hustlerprofile_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hustlerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
