# Generated by Django 4.1.4 on 2023-01-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_clientjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjob',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
