# Generated by Django 4.1.4 on 2023-01-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_alter_clientprofile_fb_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='gh_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='ig_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='li_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='pi_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='pp_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='tw_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
