# Generated by Django 4.1.4 on 2023-01-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_jobcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
