# Generated by Django 4.1.4 on 2023-01-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hustlers', '0004_alter_hustlerprofile_bio'),
        ('Clients', '0006_jobcomment_edited_at_jobcomment_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjob',
            name='hired_team',
            field=models.ManyToManyField(blank=True, related_name='hired_team', to='Hustlers.hustlerprofile'),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
