# Generated by Django 4.1.4 on 2023-01-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hustlers', '0004_alter_hustlerprofile_bio'),
        ('Clients', '0007_clientjob_hired_team_clientjob_is_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientjob',
            name='hired_team',
        ),
        migrations.AddField(
            model_name='clientjob',
            name='applied_team',
            field=models.ManyToManyField(blank=True, related_name='applied_team', to='Hustlers.hustlerprofile'),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='selected_team',
            field=models.ManyToManyField(blank=True, related_name='selected_team', to='Hustlers.hustlerprofile'),
        ),
    ]
