# Generated by Django 4.1.4 on 2023-01-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hustlers', '0004_alter_hustlerprofile_bio'),
        ('Clients', '0008_remove_clientjob_hired_team_clientjob_applied_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjob',
            name='hired_team',
            field=models.ManyToManyField(blank=True, related_name='hired_team', to='Hustlers.hustlerprofile'),
        ),
    ]
